// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrbZDlIyybsDwEU_F4acdqOGYbzSvCs9w',
    appId: '1:125541005220:web:4f4d119a9b5d6cf633b331',
    messagingSenderId: '125541005220',
    projectId: 'tccsenai',
    authDomain: 'tccsenai.firebaseapp.com',
    storageBucket: 'tccsenai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4k6NdVk9--txNc7fjCmrXDKZ1aNlfWJQ',
    appId: '1:125541005220:android:5137523bb23828fa33b331',
    messagingSenderId: '125541005220',
    projectId: 'tccsenai',
    storageBucket: 'tccsenai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDraZxs2M4ed9eE4Co9ev7HrzLhl9f7eVw',
    appId: '1:125541005220:ios:f1b377f14cf6cea033b331',
    messagingSenderId: '125541005220',
    projectId: 'tccsenai',
    storageBucket: 'tccsenai.appspot.com',
    iosClientId: '125541005220-58adi56icj10eeto73e9rrrhg29mf1h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.teste',
  );
}
